### ISSUE TITLE
Dashboard Login Not working after deploying functions

### ISSUE THREAD

**Issue by fiifibenjamin22** [carrybible/carrybible#1]
`
func_login_emailosfet215c9v6 Error: [LOGIN WITH EMAIL] Not found auth xxxxxx
<img width="1728" alt="Screenshot 2024-05-21 at 11 20 10 PM" src="https://github.com/carrybible/carrybible/assets/21160810/43494d5d-d1d2-4b21-a0d5-625761674766">
@gmail.com
    at entryFromArgs (/layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/logger/index.js:130:19)
    at Object.error (/layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/logger/index.js:116:11)
    at /workspace/lib/admin/https/func_login_email.js:71:45
    at processTicksAndRejections (internal/process/task_queues.js:95:5) `
    
    @datvudang @MilvioLua @PhilipHow @CarryBibleApp 
    
    i will be very glad to get this working.
    
    also i suggest the readme documentation is not thorough enough to guide contributors.

**Comment by fiifibenjamin22** [comment]
<img width="1728" alt="Screenshot 2024-05-21 at 11 20 10 PM" src="https://github.com/carrybible/carrybible/assets/21160810/3a70954d-c71f-4426-8905-509bf382a5d3">

@CarryBibleApp @MilvioLua @datvudang @PhilipHow this is a follow-up screen we are stuck on.

**Comment by fiifibenjamin22** [comment]
> <img alt="Screenshot 2024-05-21 at 11 20 10 PM" width="1728" src="https://private-user-images.githubusercontent.com/21160810/332607594-3a70954d-c71f-4426-8905-509bf382a5d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzQyNTksIm5iZiI6MTcxNjMzMzk1OSwicGF0aCI6Ii8yMTE2MDgxMC8zMzI2MDc1OTQtM2E3MDk1NGQtYzcxZi00NDI2LTg5MDUtNTA5YmYzODJhNWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDIzMjU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNmQwZjVhZGU3ZTllYzJkOTcxN2FjZjJiZDFjM2I1Yjk3NjhhYWM1MjdmNTU0YTEwMTAzYzk1NzkzMGUwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bjhvQWCPpS1Ht1m0brvhfrLZlvvu_Wb18VoXvBdNBDI">
> @CarryBibleApp @MilvioLua @datvudang @PhilipHow this is a follow-up screen we are stuck on.

<img width="701" alt="Screenshot 2024-05-21 at 11 26 40 PM" src="https://github.com/carrybible/carrybible/assets/21160810/c3ff445c-bc61-45c6-a864-58c2d2bb6956">

**Comment by fiifibenjamin22** [comment]
it seams, no one is available for to support this project.

**Comment by MilvioLua** [comment]
Hi, @fiifibenjamin22. 

Thank you so much for your interest in our project and for reaching out!

We wanted to let you know that this repository is provided as-is, and we are currently not offering support or assistance with setting it up. To get the project up and running, you'll need to configure all necessary keys and services, such as Firebase Authentication, Firestore, Firebase Functions, etc., on your own.

We highly recommend referring to the official documentation for each service to ensure proper setup and integration. If you run into specific issues or have questions, the respective communities and documentation can be very helpful.

We truly appreciate your understanding and wish you the best of luck with your implementation. Thank you again for your interest and support!

Best regards,
Carry Bible Team

**Comment by fiifibenjamin22** [comment]
Duplicate of #

@MilvioLua kindly reference me to the respective documentations. That can be very helpful.

Thank you in advance @MilvioLua
